[tool.poetry]
name = "stairs-world"
version = "0.1.0"
description = ""
authors = ["Mohammad Hamid <mohammad200h@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mujoco = "^3.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
